export const DISPLAY_ALERT = 'DISPLAY_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';
export const USER_REGISTRATION_BEGIN = 'USER_REGISTRATION_BEGIN';
export const USER_REGISTRATION_SUCCESSFUL = 'USER_REGISTRATION_SUCCESSFUL';
export const USER_REGISTRATION_ERROR = 'USER_REGISTRATION_ERROR';

export const USER_LOGIN_BEGIN = 'USER_LOGIN_BEGIN';
export const USER_LOGIN_SUCCESSFUL = 'USER_LOGIN_SUCCESSFUL';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';

export const SHOW_TOGGLE = 'SHOW_TOGGLE';
export const LOGOUT_USER = 'LOGOUT_USER'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const ADD_EXPENSE_BEGIN = 'ADD_EXPENSE_BEGIN';
export const ADD_EXPENSE_SUCCESS = 'ADD_EXPENSE_SUCCESS';
export const ADD_EXPENSE_ERROR = 'ADD_EXPENSE_ERROR';

export const CLEAR_INPUTS = 'CLEAR_INPUTS';