export const DISPLAY_ALERT = 'DISPLAY_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';
export const USER_REGISTRATION_BEGIN = 'USER_REGISTRATION_BEGIN';
export const USER_REGISTRATION_SUCCESSFUL = 'USER_REGISTRATION_SUCCESSFUL';
export const USER_REGISTRATION_ERROR = 'USER_REGISTRATION_ERROR';

export const USER_LOGIN_BEGIN = 'USER_REGISTRATION_BEGIN';
export const USER_LOGIN_SUCCESSFUL = 'USER_REGISTRATION_BEGIN';
export const USER_LOGIN_ERROR = 'USER_REGISTRATION_BEGIN';